[package]
name = "example-token"
version = "0.0.0"

[dependencies]
# use stdlib
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }
# use std::debug
MoveNursery = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib/nursery", rev = "main" }

[addresses]
std =  "0x1" # Specify and assign 0x1 to the named address "std"
example_token = "0x11"